feat(TMID-83): add BaseTokenGrantProvider.validate, BaseTokenGrantPro…
BrewInteractive/oauth-server pull request #37
Opened 2023-04-04 21:35 UTC by erailea

…vider.generateToken

2023-04-05 12:55 UTC, mfozmen requested changes

2023-04-05 12:55 UTC, mfozmen commented on src/main/java/com/brew/oauth20/server/model/TokenResultModel.java
> +public class TokenResultModel {
Zaten TokenModel vardı bu gereksiz olmuş.

2023-04-05 12:59 UTC, erailea commented on src/main/java/com/brew/oauth20/server/provider/tokengrant/BaseTokenGrantProvider.java
> +        var clientCredentials = clientService.decodeClientCredentials(authorizationHeader);
decodeClientCredentials kısmında bakılıyor ona. boş olması da bir malformed header değil mi bu public method çağrılıyorsa.

2023-04-06 12:32 UTC, mfozmen approved these changes

2023-04-06 12:35 UTC, merged